services:
#  nginx:
#    image: nginx:1.20
#    container_name: DEILYER_NGINX
#    ports:
#      - "8099:80"
#    volumes:
#      - ./:/app
#      - ./docker-conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    links:
#      - php
#
#  php:
#    container_name: DEILYER_PHP_FPM
#    build:
#      context: ./docker-conf/php
#    volumes:
#      - ./:/app
#    env_file:
#      - "./.env"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "3"

  app:
    build:
      context: .
      dockerfile: ./docker-conf/php/Dockerfile
    ports:
      - "8099:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: development
    env_file:
      - '.env'
    # Optionally run composer install every time the container starts
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
#    container_name: DEILYER_PHP_FPM
#    restart: unless-stopped
#    build:
#      args:
#        user: admin
#        uid: 100000
#      context: ./docker-conf/php
#    ports:
#      - "8099:80"
#    volumes:
#      - .:/var/www:rw

  db:
    image: mariadb:10.3
    container_name: DEILYER_DB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: deilyer
      MYSQL_USER: deilyer_app_user
      MYSQL_PASSWORD: password
    ports:
      - "8098:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: DEILYER_DB_ADMIN
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 8098
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 2000M
    restart: always
    ports:
      - "8097:80"
    env_file:
      - .env

volumes:
  mysql-data: